version: '3.8'
services:
  postgres:
    build:
      context: ./well-better-db
      dockerfile: Dockerfile
    image: postgres:15
    container_name: well-better-db
    environment:
      POSTGRES_USER: well_better_db_user
      POSTGRES_PASSWORD: testingPassword
      POSTGRES_DB: well-better-db
    ports:
      - "5432:5432"
    volumes:
      - ./well-better-db:/docker-entrypoint-initdb.d
      - ./testing-scripts:/lib/testing-scripts
    networks:
      - mynetwork

  spring-app:
    build:
      context: ./well-better-services
      dockerfile: Dockerfile
    image: openjdk:17
    container_name: well-better-services
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/well-better-db
      - SPRING_DATASOURCE_USERNAME=well_better_db_user
      - SPRING_DATASOURCE_PASSWORD=testingPassword
    depends_on:
      - postgres
    networks:
      - mynetwork

  angular-app:
    build:
      context: ./well-better-frontend
      dockerfile: Dockerfile
    image: node:22
    container_name: well-better-frontend
    ports:
      - "80:80"
    depends_on:
      - spring-app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:
